[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"
  base = "."

[dev]
  command = "cd client && npm run dev"
  port = 3000
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
